spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/fastkart/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
